# Generated by Django 3.1.2 on 2020-12-10 07:34

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='companies_mentioned',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='corporate_user_licence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='list_of_figures',
            field=froala_editor.fields.FroalaField(default='list of figures'),
        ),
        migrations.AddField(
            model_name='report',
            name='list_of_table',
            field=froala_editor.fields.FroalaField(default='list of tables'),
        ),
        migrations.AddField(
            model_name='report',
            name='main_category',
            field=models.CharField(choices=[('CnM', 'Chemical and Materials'), ('MnE', 'Machinery and Equipment'), ('RnCG', 'Retails and Consumer Goods'), ('HnM', 'Health and Medical'), ('FnB', 'Food and Beverages')], default='CnM', max_length=4),
        ),
        migrations.AddField(
            model_name='report',
            name='multi_user_licence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='single_user_licence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=froala_editor.fields.FroalaField(default='summary'),
        ),
        migrations.AddField(
            model_name='report',
            name='table_of_contents',
            field=froala_editor.fields.FroalaField(default='table of contents'),
        ),
    ]
