# Generated by Django 3.1.2 on 2020-12-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20201210_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='main_category',
            field=models.CharField(choices=[('CnM', 'Chemical and Materials'), ('MnE', 'Machinery and Equipment'), ('RnCG', 'Retails and Consumer Goods'), ('HnM', 'Health and Medical'), ('FnB', 'Food and Beverages')], max_length=4),
        ),
    ]
